### ISSUE TITLE
Typora beta 下载

### ISSUE THREAD

**Issue by HUGHNew** [scu-covariant/CSGuidance#1]
newest beta version:**0.11.18**
[Windows X64](https://download.typora.io/windows/typora-update-x64-1117.exe)
[Windows X86](https://download.typora.io/windows/typora-update-ia32-1117.exe)
[Linux X64/AMD64 deb](https://download.typora.io/linux/typora_0.11.18_amd64.deb)
[macOS](https://download.typora.io/mac/Typora-0.11.18.dmg)

official dev url:
- [macOS](https://typora.io/dev_release.html)
- [Windows/Linux-deb](https://typora.io/windows/dev_release.html)

**Comment by SunnyHaze** [comment]
Already merged, Thank you !
